baseURL = '/'
languageCode = 'en-us'
title = 'Weekly CCOM Challenges!'

[params]
themeColor = 'red'
showLanguageSelector = true
showLastUpdated = true

[module]
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v3'

